apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: backend
  labels:
    app: api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - image: gcr.io/jumia-app-sample/api:latest
        name: backend
        imagePullPolicy: Always
        ports:
        - containerPort: 8090

